name = "LeanSAT"
defaultTargets = ["LeanSAT", "defaultExe"]
testRunner = "Test"

[[lean_lib]]
name = "Test"

[[lean_lib]]
name = "Eval"

[[lean_lib]]
name = "LeanSAT"
precompileModules = true

[[lean_exe]]
name = "defaultExe"
root = "Main"
