on:
  push:
    branches:
      - main
  pull_request:

name: ci

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v1.4.2/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - uses: DeterminateSystems/nix-installer-action@main

      - name: install cadical
        run: nix profile install nixpkgs#cadical

      - uses: actions/checkout@v4

      - name: build
        id: build
        run: lake build

      - name: test
        if: steps.build.outcome == 'success'
        run: make test

      - name: eval
        run: make eval

      - name: Don't 'import Lean', use precise imports
        if: always()
        run: |
          ! (find LeanSAT -name "*.lean" -type f -print0 | xargs -0 grep -E -n '^import Lean$')

      - name: Find trailing whitespaces
        if: always()
        run: |
          ! (find LeanSAT -name "*.lean" -type f -print0 | xargs -0 grep -E -n ".* +$")

