on:
  push:
    branches:
      - main
  pull_request:

name: ci

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: DeterminateSystems/nix-installer-action@main

      - name: install cadical
        run: nix profile install nixpkgs#cadical

      - uses: actions/checkout@v4

      - uses: leanprover/lean-action@v1-beta
        with:
          test: true
          use-mathlib-cache: false
          use-github-cache: true

      - name: eval
        run: make eval

      - name: Don't 'import Lean', use precise imports
        if: always()
        run: |
          ! (find LeanSAT -name "*.lean" -type f -print0 | xargs -0 grep -E -n '^import Lean$')

      - name: Find trailing whitespaces
        if: always()
        run: |
          ! (find LeanSAT -name "*.lean" -type f -print0 | xargs -0 grep -E -n ".* +$")

